import {
  User,
  Ticket,
  ConfigurationItem,
  ServiceCatalogItem,
  KnowledgeArticle,
  VendorPerformanceSummary,
  AuditLogEntry,
} from '../types';

export const DEMO_USERS: User[] = [
  {
    id: 'usr-emp-1',
    employeeId: 'EMP-1042',
    name: 'Alex Rivera',
    email: 'employee.demo@enterprise-itsm.local',
    department: 'Software Engineering',
    designation: 'Senior Cloud Developer',
    location: 'Building A, Floor 3 (Seattle)',
    managerId: 'usr-mgr-1',
    managerName: 'Sarah Jenkins',
    reportingOfficerId: 'usr-mgr-1',
    role: 'Requester',
    team: 'Core Platform Engineering',
    isVendor: false,
    isActive: true,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    permissions: [
      'ticket.create',
      'ticket.view.own',
      'ticket.recall',
      'ticket.reopen',
      'ticket.resolve_confirm',
    ],
  },
  {
    id: 'usr-mgr-1',
    employeeId: 'EMP-1010',
    name: 'Sarah Jenkins',
    email: 'manager.demo@enterprise-itsm.local',
    department: 'Software Engineering',
    designation: 'Director of Engineering',
    location: 'Building A, Floor 4 (Seattle)',
    managerId: 'usr-inf-1',
    managerName: 'Marcus Vance',
    role: 'Supervisor',
    team: 'Engineering Leadership',
    isVendor: false,
    isActive: true,
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop&q=80',
    permissions: [
      'ticket.create',
      'ticket.view.own',
      'ticket.view.team',
      'approval.approve',
      'approval.reject',
      'approval.send_back',
    ],
  },
  {
    id: 'usr-inf-1',
    employeeId: 'EMP-1002',
    name: 'Marcus Vance',
    email: 'infrahead.demo@enterprise-itsm.local',
    department: 'Infrastructure & Cloud',
    designation: 'Head of Global Infrastructure',
    location: 'Executive Suite B (Austin)',
    role: 'Infra Head',
    team: 'Infrastructure Leadership',
    isVendor: false,
    isActive: true,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    permissions: [
      'ticket.view.all',
      'approval.approve',
      'approval.reject',
      'reports.view',
      'reports.invoice',
      'change.approve',
      'ticket.escalate',
    ],
  },
  {
    id: 'usr-ciso-1',
    employeeId: 'EMP-1004',
    name: 'Evelyn Reed',
    email: 'ciso.demo@enterprise-itsm.local',
    department: 'Information Security',
    designation: 'Chief Information Security Officer (CISO)',
    location: 'Security Operations Center (Austin)',
    role: 'CISO',
    team: 'Information Security & Compliance',
    isVendor: false,
    isActive: true,
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop&q=80',
    permissions: [
      'ticket.view.all',
      'approval.approve',
      'approval.reject',
      'change.approve',
      'security.audit',
      'reports.view',
    ],
  },
  {
    id: 'usr-ops-1',
    employeeId: 'EMP-1008',
    name: 'David Zhao',
    email: 'opsmanager.demo@enterprise-itsm.local',
    department: 'IT Operations & NOC',
    designation: 'Operations & NOC Manager',
    location: 'NOC Command Center (Austin)',
    role: 'Operations Manager',
    team: 'Operations Management',
    isVendor: false,
    isActive: true,
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    permissions: [
      'ticket.create',
      'ticket.view.all',
      'ticket.assign',
      'ticket.reassign',
      'ticket.pause_sla',
      'ticket.resolve',
      'ticket.close',
      'approval.approve',
      'reports.view',
      'reports.invoice',
    ],
  },
  {
    id: 'usr-l1-1',
    employeeId: 'EMP-2015',
    name: 'Kevin Patel',
    email: 'l1.demo@enterprise-itsm.local',
    department: 'IT Service Desk',
    designation: 'Tier-1 Support & NOC Specialist',
    location: 'Service Desk Pod 2',
    role: 'IT Support L1',
    team: 'Service Desk L1',
    isVendor: false,
    isActive: true,
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&auto=format&fit=crop&q=80',
    permissions: [
      'ticket.view.team',
      'ticket.view.all',
      'ticket.acknowledge',
      'ticket.reassign',
      'ticket.escalate',
      'ticket.worklog',
      'ticket.resolve',
    ],
  },
  {
    id: 'usr-l2-1',
    employeeId: 'EMP-2009',
    name: 'Rachel Green',
    email: 'l2.demo@enterprise-itsm.local',
    department: 'Cloud & Systems Engineering',
    designation: 'Cloud & Network Systems Engineer (L2)',
    location: 'Cloud Operations Center',
    role: 'Cloud Engineer',
    team: 'Cloud Operations Team',
    isVendor: false,
    isActive: true,
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80',
    permissions: [
      'ticket.view.team',
      'ticket.view.all',
      'ticket.acknowledge',
      'ticket.reassign',
      'ticket.escalate',
      'ticket.pause_sla',
      'ticket.worklog',
      'ticket.resolve',
      'task.complete',
      'kb.create',
    ],
  },
  {
    id: 'usr-l3-1',
    employeeId: 'EMP-2001',
    name: 'Vikram Seth',
    email: 'l3.demo@enterprise-itsm.local',
    department: 'Enterprise Architecture',
    designation: 'Principal Systems Architect (L3)',
    location: 'Data Center HQ',
    role: 'IT Support L3',
    team: 'Core Infrastructure L3',
    isVendor: false,
    isActive: true,
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&auto=format&fit=crop&q=80',
    permissions: [
      'ticket.view.all',
      'ticket.assign',
      'ticket.reassign',
      'ticket.pause_sla',
      'ticket.resolve',
      'ticket.close',
      'change.create',
      'problem.manage',
      'kb.create',
    ],
  },
  {
    id: 'usr-aud-1',
    employeeId: 'EMP-1090',
    name: 'Priya Sharma',
    email: 'auditor.demo@enterprise-itsm.local',
    department: 'Internal Audit & Governance',
    designation: 'Lead Technology Auditor',
    location: 'Compliance Tower C',
    role: 'Internal Auditor',
    team: 'Governance & Risk Audit',
    isVendor: false,
    isActive: true,
    avatarUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=100&auto=format&fit=crop&q=80',
    permissions: [
      'ticket.view.all',
      'audit.view',
      'reports.view',
      'asset.view',
    ],
  },
  {
    id: 'usr-adm-1',
    employeeId: 'EMP-1001',
    name: 'System Administrator',
    email: 'admin.demo@enterprise-itsm.local',
    department: 'IT Administration',
    designation: 'Enterprise Platform Administrator',
    location: 'Enterprise NOC Root',
    role: 'Super Admin',
    team: 'Platform Administration',
    isVendor: false,
    isActive: true,
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80',
    permissions: [
      'ticket.create',
      'ticket.view.all',
      'ticket.assign',
      'ticket.reassign',
      'ticket.pause_sla',
      'ticket.resolve',
      'ticket.close',
      'approval.approve',
      'approval.reject',
      'asset.manage',
      'admin.configure',
      'reports.view',
      'reports.invoice',
      'audit.view',
      'kb.create',
    ],
  },
];

// Generate an extended directory of 75 users for full organization structure
export const ALL_ORGANIZATION_USERS: User[] = [...DEMO_USERS];
const depts = [
  'Software Engineering',
  'Cloud Operations',
  'Network & Security',
  'Database Administration',
  'NOC & Monitoring',
  'Data Center Facilities',
  'DevOps & Release',
  'IT Support & Helpdesk',
  'Information Security',
  'Enterprise Storage & Backup',
];
const rolesList: User['role'][] = [
  'Requester',
  'Network Engineer',
  'Cloud Engineer',
  'Database Administrator',
  'Backup Administrator',
  'Security Analyst',
  'DevOps Engineer',
  'Data Center Engineer',
  'IT Support L1',
  'IT Support L2',
];

for (let i = 11; i <= 75; i++) {
  const dept = depts[i % depts.length];
  const role = rolesList[i % rolesList.length];
  ALL_ORGANIZATION_USERS.push({
    id: `usr-gen-${i}`,
    employeeId: `EMP-${1000 + i}`,
    name: `User ${i} (${dept.split(' ')[0]})`,
    email: `user.${i}@enterprise-itsm.local`,
    department: dept,
    designation: `${role} Specialist`,
    location: i % 2 === 0 ? 'Austin Data Center' : 'Seattle HQ',
    managerId: 'usr-mgr-1',
    managerName: 'Sarah Jenkins',
    role: role,
    team: `${dept} Team`,
    isVendor: i % 7 === 0,
    vendorName: i % 7 === 0 ? 'GlobalTech Infotech Services' : undefined,
    isActive: true,
    permissions: ['ticket.create', 'ticket.view.own', 'ticket.view.team'],
  });
}

export const SEEDED_CIS: ConfigurationItem[] = [
  {
    id: 'ci-vm-101',
    ciNumber: 'CI-VM-00101',
    name: 'prd-app-web-01.corp',
    ciClass: 'Virtual Machine',
    ipAddress: '10.240.12.45',
    environment: 'PROD',
    status: 'ACTIVE',
    owner: 'Alex Rivera',
    dataCenter: 'DC-West-01 (Equinix SV5)',
    operatingSystem: 'Red Hat Enterprise Linux 9.2',
    cpu: '8 vCPU',
    ram: '32 GB',
    disk: '250 GB NVMe',
    relationships: [
      { id: 'rel-1', relationshipType: 'hosted on', targetCIId: 'ci-hyp-01', targetCIName: 'esx-cluster-prod-01', targetCIClass: 'Physical Server' },
      { id: 'rel-2', relationshipType: 'uses', targetCIId: 'ci-db-01', targetCIName: 'prd-mysql-cluster-primary', targetCIClass: 'Database' },
      { id: 'rel-3', relationshipType: 'behind', targetCIId: 'ci-lb-01', targetCIName: 'f5-bigip-edge-lb01', targetCIClass: 'Load Balancer' },
      { id: 'rel-4', relationshipType: 'protected by', targetCIId: 'ci-fw-01', targetCIName: 'paloalto-ha-perimeter', targetCIClass: 'Firewall' },
      { id: 'rel-5', relationshipType: 'monitored by', targetCIId: 'ci-mon-01', targetCIName: 'zabbix-enterprise-cluster', targetCIClass: 'Monitoring Device' },
      { id: 'rel-6', relationshipType: 'backed up by', targetCIId: 'ci-bkp-01', targetCIName: 'veeam-appliance-dr', targetCIClass: 'Backup Server' },
    ],
  },
  {
    id: 'ci-vm-102',
    ciNumber: 'CI-VM-00102',
    name: 'prd-app-api-01.corp',
    ciClass: 'Virtual Machine',
    ipAddress: '10.240.12.46',
    environment: 'PROD',
    status: 'ACTIVE',
    owner: 'Alex Rivera',
    dataCenter: 'DC-West-01 (Equinix SV5)',
    operatingSystem: 'Ubuntu 22.04 LTS',
    cpu: '16 vCPU',
    ram: '64 GB',
    disk: '500 GB NVMe',
    relationships: [
      { id: 'rel-7', relationshipType: 'hosted on', targetCIId: 'ci-hyp-01', targetCIName: 'esx-cluster-prod-01', targetCIClass: 'Physical Server' },
      { id: 'rel-8', relationshipType: 'uses', targetCIId: 'ci-db-01', targetCIName: 'prd-mysql-cluster-primary', targetCIClass: 'Database' },
      { id: 'rel-9', relationshipType: 'protected by', targetCIId: 'ci-fw-01', targetCIName: 'paloalto-ha-perimeter', targetCIClass: 'Firewall' },
    ],
  },
  {
    id: 'ci-db-01',
    ciNumber: 'CI-DB-00001',
    name: 'prd-mysql-cluster-primary',
    ciClass: 'Database',
    ipAddress: '10.240.15.10',
    environment: 'PROD',
    status: 'ACTIVE',
    owner: 'Vikram Seth',
    dataCenter: 'DC-West-01 (Equinix SV5)',
    operatingSystem: 'Enterprise MySQL 8.0 Group Replication',
    cpu: '32 vCPU',
    ram: '128 GB',
    disk: '2 TB SSD RAID-10',
    relationships: [
      { id: 'rel-10', relationshipType: 'backed up by', targetCIId: 'ci-bkp-01', targetCIName: 'veeam-appliance-dr', targetCIClass: 'Backup Server' },
      { id: 'rel-11', relationshipType: 'protected by', targetCIId: 'ci-fw-01', targetCIName: 'paloalto-ha-perimeter', targetCIClass: 'Firewall' },
    ],
  },
  {
    id: 'ci-fw-01',
    ciNumber: 'CI-SEC-00001',
    name: 'paloalto-ha-perimeter',
    ciClass: 'Firewall',
    ipAddress: '10.240.1.1',
    environment: 'PROD',
    status: 'ACTIVE',
    owner: 'Evelyn Reed',
    dataCenter: 'DC-West-01 (Equinix SV5)',
    operatingSystem: 'PAN-OS 11.0.2',
    relationships: [],
  },
  {
    id: 'ci-lb-01',
    ciNumber: 'CI-NET-00002',
    name: 'f5-bigip-edge-lb01',
    ciClass: 'Load Balancer',
    ipAddress: '10.240.1.254',
    environment: 'PROD',
    status: 'ACTIVE',
    owner: 'Rachel Green',
    dataCenter: 'DC-West-01 (Equinix SV5)',
    relationships: [],
  },
  {
    id: 'ci-rtr-01',
    ciNumber: 'CI-NET-00001',
    name: 'cisco-asr9000-border-gw',
    ciClass: 'Router',
    ipAddress: '198.51.100.1',
    environment: 'PROD',
    status: 'ACTIVE',
    owner: 'David Zhao',
    dataCenter: 'DC-West-01 (Equinix SV5)',
    relationships: [],
  },
  {
    id: 'ci-mon-01',
    ciNumber: 'CI-MON-00001',
    name: 'zabbix-enterprise-cluster',
    ciClass: 'Monitoring Device',
    ipAddress: '10.240.8.50',
    environment: 'PROD',
    status: 'ACTIVE',
    owner: 'David Zhao',
    dataCenter: 'DC-West-01 (Equinix SV5)',
    relationships: [],
  },
  {
    id: 'ci-bkp-01',
    ciNumber: 'CI-STR-00001',
    name: 'veeam-appliance-dr',
    ciClass: 'Backup Server',
    ipAddress: '10.240.9.12',
    environment: 'PROD',
    status: 'ACTIVE',
    owner: 'Vikram Seth',
    dataCenter: 'DC-East-02 (Ashburn)',
    relationships: [],
  },
];

export const SERVICE_CATALOG_ITEMS: ServiceCatalogItem[] = [
  {
    id: 'cat-vm-provision',
    name: 'Virtual Machine Provisioning',
    category: 'Cloud & VM',
    description: 'Request one or multiple Enterprise VMs (Web, App, DB, Cache, Kafka) with automated network, security, backup, and monitoring tasks.',
    iconName: 'Server',
    estimatedSLA: '8 Hours (Standard)',
    approvalRequired: true,
    defaultPriority: 'P3',
    ticketType: 'VM Request',
    requiresVMWorkflow: true,
  },
  {
    id: 'cat-firewall-whitelist',
    name: 'Firewall Port & IP Whitelist Request',
    category: 'Network & Security',
    description: 'Request ingress/egress firewall policy changes, port opening, or IP whitelisting with CISO security verification.',
    iconName: 'Shield',
    estimatedSLA: '4 Hours',
    approvalRequired: true,
    defaultPriority: 'P3',
    ticketType: 'Firewall Whitelist',
    requiresFirewallWorkflow: true,
  },
  {
    id: 'cat-res-scale',
    name: 'VM Resource Scaling (vCPU/RAM/Disk)',
    category: 'Cloud & VM',
    description: 'Request on-demand compute or storage expansion for existing production or non-production virtual machines.',
    iconName: 'Cpu',
    estimatedSLA: '4 Hours',
    approvalRequired: true,
    defaultPriority: 'P3',
    ticketType: 'Service Request',
  },
  {
    id: 'cat-db-provision',
    name: 'Database Instance or Schema Creation',
    category: 'Database',
    description: 'Request dedicated MySQL, PostgreSQL, or Redis database cluster instance with high availability configuration.',
    iconName: 'Database',
    estimatedSLA: '6 Hours',
    approvalRequired: true,
    defaultPriority: 'P3',
    ticketType: 'Database Request',
  },
  {
    id: 'cat-incident-report',
    name: 'Report Production Outage / Incident',
    category: 'Infrastructure Maintenance',
    description: 'Raise an immediate incident for service disruption, connectivity drops, server failure, or system alerts.',
    iconName: 'AlertTriangle',
    estimatedSLA: '15m Response (P1) / 2h Fix',
    approvalRequired: false,
    defaultPriority: 'P2',
    ticketType: 'Incident',
  },
  {
    id: 'cat-change-request',
    name: 'Submit RFC / Production Change',
    category: 'Infrastructure Maintenance',
    description: 'Submit a Standard, Normal, or Emergency Change Request for CAB evaluation, maintenance window booking, and rollback plans.',
    iconName: 'GitPullRequest',
    estimatedSLA: '24 Hours (CAB Review)',
    approvalRequired: true,
    defaultPriority: 'P3',
    ticketType: 'Change Request',
  },
  {
    id: 'cat-backup-restore',
    name: 'Backup Review & Restoration Request',
    category: 'Backup & Storage',
    description: 'Request scheduled backup verification, snapshot retention change, or emergency file/database recovery.',
    iconName: 'Archive',
    estimatedSLA: '2 Hours',
    approvalRequired: true,
    defaultPriority: 'P2',
    ticketType: 'Backup Review',
  },
  {
    id: 'cat-endpoint-byod',
    name: 'Endpoint Support & BYOD Compliance',
    category: 'Endpoint & Helpdesk',
    description: 'Register corporate laptops, BYOD devices, mobile MDM certificates, or request hardware replacements.',
    iconName: 'Laptop',
    estimatedSLA: '8 Hours',
    approvalRequired: true,
    defaultPriority: 'P4',
    ticketType: 'Endpoint Support',
  },
];

export const INITIAL_TICKETS: Ticket[] = [
  // 1. VM Request with complete multi-task child work orders
  {
    id: 'tkt-vm-001',
    ticketNumber: 'VMR-2026-000001',
    title: 'Provision 3-Tier Microservices Stack (Web, API, Redis Cache)',
    description: 'Provision 3 production virtual machines for Project Falcon real-time payment aggregation: 1x Web proxy (Nginx), 1x API service (Node/Go), 1x High-speed Redis 7.2 cluster node.',
    ticketType: 'VM Request',
    status: 'IN_PROGRESS',
    priority: 'P2',
    impact: 'Department',
    urgency: 'High',
    category: 'Cloud & VM',
    subcategory: 'Virtual Machine Provisioning',
    service: 'Core Platform Hosting',
    department: 'Software Engineering',
    requesterId: 'usr-emp-1',
    requesterName: 'Alex Rivera',
    requesterEmail: 'employee.demo@enterprise-itsm.local',
    requesterDepartment: 'Software Engineering',
    currentAssignmentGroup: 'Cloud Operations Team',
    currentAssigneeId: 'usr-l2-1',
    currentAssigneeName: 'Rachel Green',
    assignedLevel: 'L2',
    businessOwner: 'Sarah Jenkins',
    technicalOwner: 'Alex Rivera',
    environment: 'PROD',
    createdAt: '2026-09-14T08:30:00Z',
    updatedAt: '2026-09-15T03:45:00Z',
    sla: {
      priority: 'P2',
      responseTargetMinutes: 30,
      resolutionTargetMinutes: 480, // 8 hours
      responseSLAStart: '2026-09-14T08:30:00Z',
      responseSLAEnd: '2026-09-14T08:45:00Z',
      responseSLAMet: true,
      resolutionSLAStart: '2026-09-14T08:30:00Z',
      resolutionSLATarget: '2026-09-15T16:30:00Z',
      elapsedMinutes: 340,
      pausedMinutes: 0,
      remainingMinutes: 140,
      percentageConsumed: 70.8,
      isPaused: false,
      isBreached: false,
      clockEvents: [
        {
          id: 'clk-1',
          eventType: 'STARTED',
          timestamp: '2026-09-14T08:30:00Z',
          actorName: 'System Engine',
          justification: 'Ticket submitted and queued',
        },
      ],
    },
    approvals: [
      {
        id: 'app-1',
        stageName: 'Supervisor Approval',
        approverRole: 'Supervisor',
        approverUserId: 'usr-mgr-1',
        approverName: 'Sarah Jenkins',
        status: 'APPROVED',
        actionDate: '2026-09-14T09:10:00Z',
        comments: 'Approved for Q3 Payment Gateway rollout.',
        isMandatory: true,
      },
      {
        id: 'app-2',
        stageName: 'Infra Head Approval',
        approverRole: 'Infra Head',
        approverUserId: 'usr-inf-1',
        approverName: 'Marcus Vance',
        status: 'APPROVED',
        actionDate: '2026-09-14T10:15:00Z',
        comments: 'Capacity confirmed in Equinix SV5 DC. Approved.',
        isMandatory: true,
      },
      {
        id: 'app-3',
        stageName: 'Operations Manager Dispatch',
        approverRole: 'Operations Manager',
        approverUserId: 'usr-ops-1',
        approverName: 'David Zhao',
        status: 'APPROVED',
        actionDate: '2026-09-14T10:30:00Z',
        comments: 'Assigned to Cloud Ops Engineer Rachel Green for execution.',
        isMandatory: true,
      },
    ],
    tasks: [
      {
        id: 'tsk-01',
        taskNumber: 'TASK-001',
        title: 'Cloud Provisioning: Create 3x Virtual Machines in VMware vSphere',
        description: 'Deploy RHEL 9 templates, assign vCPU (8/16/8) and RAM (16/32/16 GB).',
        team: 'Cloud Operations Team',
        assigneeName: 'Rachel Green',
        status: 'COMPLETED',
        olaTargetHours: 3,
        olaElapsedHours: 2.2,
        completedAt: '2026-09-14T13:00:00Z',
        completedBy: 'Rachel Green',
        outputSummary: 'VMs created: falcon-web-01, falcon-api-01, falcon-redis-01.',
      },
      {
        id: 'tsk-02',
        taskNumber: 'TASK-002',
        title: 'Network Work Order: VLAN Routing & Static IP Assignment',
        description: 'Allocate IPs in VLAN 240 (10.240.12.50 - 10.240.12.52) and configure DNS entries.',
        team: 'Network & Security',
        assigneeName: 'Rachel Green',
        status: 'COMPLETED',
        olaTargetHours: 2,
        olaElapsedHours: 1.1,
        completedAt: '2026-09-14T14:15:00Z',
        completedBy: 'Rachel Green',
        outputSummary: 'IPs assigned and reverse DNS configured in Infoblox.',
      },
      {
        id: 'tsk-03',
        taskNumber: 'TASK-003',
        title: 'Firewall Policy: Configure Inter-VLAN Ports (80/443, 8080, 6379)',
        description: 'Open communication between Web -> API (8080) and API -> Redis (6379). Deny public direct Redis access.',
        team: 'Network & Security',
        assigneeName: 'Rachel Green',
        status: 'IN_PROGRESS',
        olaTargetHours: 1,
        olaElapsedHours: 0.6,
      },
      {
        id: 'tsk-04',
        taskNumber: 'TASK-004',
        title: 'Storage & Backup Policy: Daily Veeam Incremental Snapshot',
        description: 'Attach Gold SLA daily snapshot backup policy with 30-day retention.',
        team: 'Backup & Storage',
        status: 'QUEUED',
        olaTargetHours: 1,
        olaElapsedHours: 0,
      },
      {
        id: 'tsk-05',
        taskNumber: 'TASK-005',
        title: 'NOC Monitoring: Install Zabbix & Prometheus Node Exporters',
        description: 'Configure CPU, memory, disk threshold alerts and send to NOC Slack/PagerDuty.',
        team: 'NOC & Monitoring',
        status: 'PENDING',
        olaTargetHours: 1,
        olaElapsedHours: 0,
      },
      {
        id: 'tsk-06',
        taskNumber: 'TASK-006',
        title: 'Security Hardening: CIS Benchmark Level 1 & CrowdStrike EDR Agent',
        description: 'Apply ansible-hardening role and ensure agent reports healthy to Falcon console.',
        team: 'Information Security',
        status: 'PENDING',
        olaTargetHours: 1,
        olaElapsedHours: 0,
      },
    ],
    activities: [
      {
        id: 'act-1',
        timestamp: '2026-09-14T08:30:00Z',
        actorId: 'usr-emp-1',
        actorName: 'Alex Rivera',
        actorRole: 'Requester',
        action: 'Ticket Created',
        details: 'Submitted parent request VMR-2026-000001 with 3 VM components.',
        type: 'STATUS_CHANGE',
      },
      {
        id: 'act-2',
        timestamp: '2026-09-14T09:10:00Z',
        actorId: 'usr-mgr-1',
        actorName: 'Sarah Jenkins',
        actorRole: 'Supervisor',
        action: 'Stage Approved',
        details: 'Approved stage: Supervisor Approval.',
        type: 'APPROVAL',
      },
      {
        id: 'act-3',
        timestamp: '2026-09-14T10:15:00Z',
        actorId: 'usr-inf-1',
        actorName: 'Marcus Vance',
        actorRole: 'Infra Head',
        action: 'Stage Approved',
        details: 'Approved stage: Infra Head Approval.',
        type: 'APPROVAL',
      },
      {
        id: 'act-4',
        timestamp: '2026-09-14T13:00:00Z',
        actorId: 'usr-l2-1',
        actorName: 'Rachel Green',
        actorRole: 'Cloud Engineer',
        action: 'Task Completed',
        details: 'Completed work order TASK-001 (Cloud Provisioning).',
        type: 'TASK',
      },
    ],
    worklogs: [
      {
        id: 'wkl-1',
        ticketId: 'tkt-vm-001',
        engineerId: 'usr-l2-1',
        engineerName: 'Rachel Green',
        team: 'Cloud Operations Team',
        startTime: '2026-09-14T11:00:00Z',
        endTime: '2026-09-14T13:00:00Z',
        minutesSpent: 120,
        activity: 'Cloned templates from gold image, adjusted core allocations, verified root disk partitions.',
        isPrivate: false,
        actionTaken: 'Provisioned 3 VMs in vSphere Cluster 1',
      },
    ],
    credentialHandover: {
      isHandedOver: false,
      temporaryUsername: 'svc-falcon-deploy',
      maskedPassword: '••••••••••••••••',
    },
    customFields: {
      numberOfVMs: 3,
      dataCenter: 'DC-West-01 (Equinix SV5)',
      os: 'Red Hat Enterprise Linux 9.2',
      vCpuTotal: 32,
      ramGbTotal: 64,
      diskGbTotal: 600,
    },
  },

  // 2. Firewall / Whitelist Request pending CISO approval
  {
    id: 'tkt-fw-002',
    ticketNumber: 'REQ-2026-000004',
    title: 'Production Ingress Whitelist: Partner Payment Gateway Webhook (Port 8443)',
    description: 'Open TCP port 8443 ingress from Stripe/Adyen webhook IP block (198.51.100.40/29) to production DMZ API load balancer 10.240.1.254. Required for new recurring billing engine.',
    ticketType: 'Firewall Whitelist',
    status: 'PENDING_APPROVAL',
    priority: 'P2',
    impact: 'Multiple Departments',
    urgency: 'High',
    category: 'Network & Security',
    subcategory: 'Firewall Port & Whitelist',
    service: 'Perimeter Security',
    department: 'Software Engineering',
    requesterId: 'usr-emp-1',
    requesterName: 'Alex Rivera',
    requesterEmail: 'employee.demo@enterprise-itsm.local',
    requesterDepartment: 'Software Engineering',
    currentAssignmentGroup: 'Information Security',
    businessOwner: 'Sarah Jenkins',
    environment: 'PROD',
    createdAt: '2026-09-15T02:00:00Z',
    updatedAt: '2026-09-15T04:10:00Z',
    sla: {
      priority: 'P2',
      responseTargetMinutes: 30,
      resolutionTargetMinutes: 240,
      responseSLAStart: '2026-09-15T02:00:00Z',
      responseSLAEnd: '2026-09-15T02:15:00Z',
      responseSLAMet: true,
      resolutionSLAStart: '2026-09-15T02:00:00Z',
      resolutionSLATarget: '2026-09-15T06:00:00Z',
      elapsedMinutes: 190,
      pausedMinutes: 0,
      remainingMinutes: 50,
      percentageConsumed: 79.2,
      isPaused: false,
      isBreached: false,
      clockEvents: [
        {
          id: 'clk-fw-1',
          eventType: 'STARTED',
          timestamp: '2026-09-15T02:00:00Z',
          actorName: 'System Engine',
        },
      ],
    },
    approvals: [
      {
        id: 'app-fw-1',
        stageName: 'Supervisor Approval',
        approverRole: 'Supervisor',
        approverUserId: 'usr-mgr-1',
        approverName: 'Sarah Jenkins',
        status: 'APPROVED',
        actionDate: '2026-09-15T02:30:00Z',
        comments: 'Verified business requirement with FinOps team.',
        isMandatory: true,
      },
      {
        id: 'app-fw-2',
        stageName: 'Security Review & CISO Sign-off',
        approverRole: 'CISO',
        approverUserId: 'usr-ciso-1',
        approverName: 'Evelyn Reed',
        status: 'PENDING',
        isMandatory: true,
      },
      {
        id: 'app-fw-3',
        stageName: 'Infra Head Approval',
        approverRole: 'Infra Head',
        approverUserId: 'usr-inf-1',
        approverName: 'Marcus Vance',
        status: 'PENDING',
        isMandatory: true,
      },
      {
        id: 'app-fw-4',
        stageName: 'NOC / Network Implementation',
        approverRole: 'Operations Manager',
        approverUserId: 'usr-ops-1',
        approverName: 'David Zhao',
        status: 'PENDING',
        isMandatory: true,
      },
    ],
    tasks: [],
    activities: [
      {
        id: 'act-fw-1',
        timestamp: '2026-09-15T02:00:00Z',
        actorId: 'usr-emp-1',
        actorName: 'Alex Rivera',
        actorRole: 'Requester',
        action: 'Submitted Request',
        details: 'Created Firewall Whitelist ticket REQ-2026-000004.',
        type: 'STATUS_CHANGE',
      },
      {
        id: 'act-fw-2',
        timestamp: '2026-09-15T02:30:00Z',
        actorId: 'usr-mgr-1',
        actorName: 'Sarah Jenkins',
        actorRole: 'Supervisor',
        action: 'Stage Approved',
        details: 'Approved stage 1. Forwarded to CISO Evelyn Reed.',
        type: 'APPROVAL',
      },
    ],
    worklogs: [],
    customFields: {
      sourceIp: '198.51.100.40/29',
      destinationIp: '10.240.1.254',
      port: '8443',
      protocol: 'TCP',
      direction: 'Ingress (Internet to DMZ)',
      urlFqdn: 'webhook.enterprise-payments.com',
      dataClassification: 'Confidential (PCI-DSS Scoped)',
      temporary: false,
    },
  },

  // 3. P1 Major Incident with Third-Party ISP Root Cause (Scenario 5 testing)
  {
    id: 'tkt-inc-003',
    ticketNumber: 'INC-2026-000002',
    title: 'Core Border Router BGP Session Flapping - Upstream ISP Carrier Outage',
    description: 'Border Gateway Router cisco-asr9000-border-gw experienced 48 BGP flaps in 20 minutes due to physical fiber cut on Lumen upstream transit circuit. Latency spiked to 240ms across West DC.',
    ticketType: 'Incident',
    status: 'IN_PROGRESS',
    priority: 'P1',
    impact: 'Enterprise',
    urgency: 'Critical',
    category: 'Network & Security',
    subcategory: 'Core Routing & BGP',
    service: 'Corporate WAN & Internet Backbone',
    department: 'NOC & Monitoring',
    requesterId: 'usr-l1-1',
    requesterName: 'Kevin Patel',
    requesterEmail: 'l1.demo@enterprise-itsm.local',
    requesterDepartment: 'NOC & Monitoring',
    currentAssignmentGroup: 'Network & Security',
    currentAssigneeId: 'usr-l2-1',
    currentAssigneeName: 'Rachel Green',
    assignedLevel: 'L2',
    businessOwner: 'Marcus Vance',
    affectedCIId: 'ci-rtr-01',
    affectedCIName: 'cisco-asr9000-border-gw',
    affectedIP: '198.51.100.1',
    environment: 'PROD',
    isMajorIncident: true,
    majorIncidentManager: 'David Zhao',
    bridgeDetails: 'https://bridge.enterprise.internal/incident-p1-bgp-flap',
    createdAt: '2026-09-15T04:00:00Z',
    updatedAt: '2026-09-15T05:10:00Z',
    sla: {
      priority: 'P1',
      responseTargetMinutes: 15,
      resolutionTargetMinutes: 120, // 2 hours
      responseSLAStart: '2026-09-15T04:00:00Z',
      responseSLAEnd: '2026-09-15T04:08:00Z',
      responseSLAMet: true,
      resolutionSLAStart: '2026-09-15T04:00:00Z',
      resolutionSLATarget: '2026-09-15T06:00:00Z',
      elapsedMinutes: 70,
      pausedMinutes: 0,
      remainingMinutes: 50,
      percentageConsumed: 58.3,
      isPaused: false,
      isBreached: false,
      clockEvents: [
        {
          id: 'clk-inc-1',
          eventType: 'STARTED',
          timestamp: '2026-09-15T04:00:00Z',
          actorName: 'NOC Zabbix Webhook',
        },
      ],
    },
    thirdPartyDependency: {
      isThirdParty: true,
      providerName: 'Lumen Technologies (Tier 1 ISP)',
      externalTicketNumber: 'LMN-TKT-9920194',
      downtimeMinutes: 34,
      delayAttribution: 'ISP Issue',
      justification: 'Metro fiber cut confirmed at 4th Ave sub-station. Traffic automatically re-routed to secondary Zayo 100G circuit.',
    },
    approvals: [],
    tasks: [],
    activities: [
      {
        id: 'act-inc-1',
        timestamp: '2026-09-15T04:00:00Z',
        actorId: 'usr-l1-1',
        actorName: 'Kevin Patel',
        actorRole: 'NOC L1',
        action: 'Incident Created',
        details: 'Raised P1 Critical incident from automated SNMP trap.',
        type: 'STATUS_CHANGE',
      },
      {
        id: 'act-inc-2',
        timestamp: '2026-09-15T04:08:00Z',
        actorId: 'usr-l1-1',
        actorName: 'Kevin Patel',
        actorRole: 'NOC L1',
        action: 'Escalated L1 -> L2',
        details: 'Determined BGP neighbor flap required Network L2 routing specialist.',
        type: 'ASSIGNMENT',
      },
      {
        id: 'act-inc-3',
        timestamp: '2026-09-15T04:12:00Z',
        actorId: 'usr-ops-1',
        actorName: 'David Zhao',
        actorRole: 'Operations Manager',
        action: 'Major Incident Bridge Declared',
        details: 'Bridge opened. Ops Manager appointed incident commander.',
        type: 'COMMENT',
      },
    ],
    worklogs: [
      {
        id: 'wkl-inc-1',
        ticketId: 'tkt-inc-003',
        engineerId: 'usr-l2-1',
        engineerName: 'Rachel Green',
        team: 'Network & Security',
        startTime: '2026-09-15T04:15:00Z',
        endTime: '2026-09-15T05:00:00Z',
        minutesSpent: 45,
        activity: 'Checked BGP summary: Peer 198.51.100.2 down. Dampened unstable route advertisements and forced MED preference over Zayo circuit.',
        isPrivate: false,
        actionTaken: 'Traffic successfully diverted to secondary 100G link. BGP restored.',
      },
    ],
  },

  // 4. Incident with SLA Paused (Waiting for Approved Maintenance Window)
  {
    id: 'tkt-inc-004',
    ticketNumber: 'INC-2026-000003',
    title: 'High Storage Pool IOPS Latency on NetApp Storage Array Shelf 3',
    description: 'Storage controller node B reporting disk latency spikes > 85ms on Volume vol_app_prod_04. Vendor recommend firmware upgrade on NVRAM module.',
    ticketType: 'Incident',
    status: 'ON_HOLD',
    priority: 'P3',
    impact: 'Department',
    urgency: 'Medium',
    category: 'Enterprise Storage & Backup',
    subcategory: 'SAN/NAS Latency',
    service: 'SAN Storage Cluster',
    department: 'Cloud Operations',
    requesterId: 'usr-l2-1',
    requesterName: 'Rachel Green',
    requesterEmail: 'l2.demo@enterprise-itsm.local',
    requesterDepartment: 'Cloud Operations',
    currentAssignmentGroup: 'Core Infrastructure L3',
    currentAssigneeId: 'usr-l3-1',
    currentAssigneeName: 'Vikram Seth',
    assignedLevel: 'L3',
    businessOwner: 'Marcus Vance',
    environment: 'PROD',
    createdAt: '2026-09-14T14:00:00Z',
    updatedAt: '2026-09-15T01:00:00Z',
    sla: {
      priority: 'P3',
      responseTargetMinutes: 120,
      resolutionTargetMinutes: 480,
      responseSLAStart: '2026-09-14T14:00:00Z',
      responseSLAEnd: '2026-09-14T14:35:00Z',
      responseSLAMet: true,
      resolutionSLAStart: '2026-09-14T14:00:00Z',
      resolutionSLATarget: '2026-09-15T18:00:00Z',
      elapsedMinutes: 210,
      pausedMinutes: 240,
      remainingMinutes: 270,
      percentageConsumed: 43.75,
      isPaused: true,
      isBreached: false,
      pauseReason: 'Waiting for Approved Maintenance Window',
      pausedAt: '2026-09-14T17:30:00Z',
      pauseJustification: 'Firmware controller flash requires 15-minute failover pause. Scheduled for tonight 02:00 AM UTC maintenance window.',
      expectedResumeTime: '2026-09-15T02:00:00Z',
      pausedBy: 'Vikram Seth',
      clockEvents: [
        {
          id: 'clk-hold-1',
          eventType: 'STARTED',
          timestamp: '2026-09-14T14:00:00Z',
          actorName: 'System Engine',
        },
        {
          id: 'clk-hold-2',
          eventType: 'PAUSED',
          timestamp: '2026-09-14T17:30:00Z',
          actorName: 'Vikram Seth',
          reason: 'Waiting for Approved Maintenance Window',
          justification: 'Scheduled for tonight maintenance window 02:00 UTC.',
        },
      ],
    },
    approvals: [],
    tasks: [],
    activities: [
      {
        id: 'act-hld-1',
        timestamp: '2026-09-14T17:30:00Z',
        actorId: 'usr-l3-1',
        actorName: 'Vikram Seth',
        actorRole: 'Principal Systems Architect (L3)',
        action: 'SLA Clock Paused',
        details: 'Paused SLA. Reason: Waiting for Approved Maintenance Window. Justification logged in clock history.',
        type: 'SLA_HOLD',
        oldValue: 'IN_PROGRESS',
        newValue: 'ON_HOLD',
      },
    ],
    worklogs: [],
  },

  // 5. Resolved Incident ready for Knowledge Article generation & Requester confirmation
  {
    id: 'tkt-inc-005',
    ticketNumber: 'INC-2026-000005',
    title: 'MySQL Connection Pool Exhaustion on prd-mysql-cluster-primary',
    description: 'Application services threw "Too many connections" errors. Max connections capped at 1000 with 980 orphaned idle PHP/Worker connections.',
    ticketType: 'Incident',
    status: 'RESOLVED',
    priority: 'P2',
    impact: 'Department',
    urgency: 'High',
    category: 'Database Administration',
    subcategory: 'Connection Pool',
    service: 'Enterprise MySQL 8.0 Cluster',
    department: 'Software Engineering',
    requesterId: 'usr-emp-1',
    requesterName: 'Alex Rivera',
    requesterEmail: 'employee.demo@enterprise-itsm.local',
    requesterDepartment: 'Software Engineering',
    currentAssignmentGroup: 'Database Administration',
    currentAssigneeId: 'usr-l3-1',
    currentAssigneeName: 'Vikram Seth',
    assignedLevel: 'L3',
    businessOwner: 'Sarah Jenkins',
    affectedCIId: 'ci-db-01',
    affectedCIName: 'prd-mysql-cluster-primary',
    affectedIP: '10.240.15.10',
    environment: 'PROD',
    createdAt: '2026-09-13T10:00:00Z',
    updatedAt: '2026-09-13T12:45:00Z',
    resolvedAt: '2026-09-13T12:45:00Z',
    resolutionSummary: 'Identified leaked rogue cron job running without connection pooling. Killed 350 sleeping queries using pt-kill, increased max_connections to 2500 dynamically via SET GLOBAL, and tuned wait_timeout to 60s.',
    resolutionCode: 'Configuration Tuning & Process Termination',
    resolutionWorkaround: 'Run pt-kill --busy-time 60 --print --kill to prune leaked idle connections.',
    sla: {
      priority: 'P2',
      responseTargetMinutes: 30,
      resolutionTargetMinutes: 240,
      responseSLAStart: '2026-09-13T10:00:00Z',
      responseSLAEnd: '2026-09-13T10:14:00Z',
      responseSLAMet: true,
      resolutionSLAStart: '2026-09-13T10:00:00Z',
      resolutionSLATarget: '2026-09-13T14:00:00Z',
      resolutionSLAEnd: '2026-09-13T12:45:00Z',
      elapsedMinutes: 165,
      pausedMinutes: 0,
      remainingMinutes: 75,
      percentageConsumed: 68.75,
      isPaused: false,
      isBreached: false,
      clockEvents: [
        {
          id: 'clk-res-1',
          eventType: 'STARTED',
          timestamp: '2026-09-13T10:00:00Z',
          actorName: 'System Engine',
        },
        {
          id: 'clk-res-2',
          eventType: 'MET',
          timestamp: '2026-09-13T12:45:00Z',
          actorName: 'Vikram Seth',
        },
      ],
    },
    approvals: [],
    tasks: [],
    activities: [
      {
        id: 'act-res-1',
        timestamp: '2026-09-13T12:45:00Z',
        actorId: 'usr-l3-1',
        actorName: 'Vikram Seth',
        actorRole: 'Principal Systems Architect (L3)',
        action: 'Incident Resolved',
        details: 'Resolution entered. Sent resolution confirmation notification to requester Alex Rivera.',
        type: 'STATUS_CHANGE',
        oldValue: 'IN_PROGRESS',
        newValue: 'RESOLVED',
      },
    ],
    worklogs: [
      {
        id: 'wkl-res-1',
        ticketId: 'tkt-inc-005',
        engineerId: 'usr-l3-1',
        engineerName: 'Vikram Seth',
        team: 'Database Administration',
        startTime: '2026-09-13T10:30:00Z',
        endTime: '2026-09-13T12:30:00Z',
        minutesSpent: 120,
        activity: 'Analyzed slow query log, inspected processlist, executed connection pruning script and adjusted MySQL runtime parameters.',
        isPrivate: false,
        actionTaken: 'Pruned leaked connections and permanently updated ansible my.cnf template.',
      },
    ],
  },

  // 6. Recalled Ticket Example (Scenario 2 testing)
  {
    id: 'tkt-req-006',
    ticketNumber: 'REQ-2026-000009',
    title: 'Accidental Duplicate: Developer Sandbox VM Request',
    description: 'Submitted request with incorrect RAM allocation (intended 16GB, entered 256GB). Recalled by requester before provisioning started.',
    ticketType: 'VM Request',
    status: 'RECALLED',
    priority: 'P4',
    impact: 'Individual',
    urgency: 'Low',
    category: 'Cloud & VM',
    subcategory: 'Virtual Machine Provisioning',
    service: 'Developer Sandbox',
    department: 'Software Engineering',
    requesterId: 'usr-emp-1',
    requesterName: 'Alex Rivera',
    requesterEmail: 'employee.demo@enterprise-itsm.local',
    requesterDepartment: 'Software Engineering',
    currentAssignmentGroup: 'Cloud Operations Team',
    businessOwner: 'Sarah Jenkins',
    createdAt: '2026-09-14T11:00:00Z',
    updatedAt: '2026-09-14T11:15:00Z',
    recalledAt: '2026-09-14T11:15:00Z',
    sla: {
      priority: 'P4',
      responseTargetMinutes: 240,
      resolutionTargetMinutes: 2880,
      responseSLAStart: '2026-09-14T11:00:00Z',
      resolutionSLAStart: '2026-09-14T11:00:00Z',
      resolutionSLATarget: '2026-09-16T11:00:00Z',
      elapsedMinutes: 15,
      pausedMinutes: 0,
      remainingMinutes: 2865,
      percentageConsumed: 0.5,
      isPaused: true,
      isBreached: false,
      clockEvents: [],
    },
    approvals: [],
    tasks: [],
    activities: [
      {
        id: 'act-rcl-1',
        timestamp: '2026-09-14T11:00:00Z',
        actorId: 'usr-emp-1',
        actorName: 'Alex Rivera',
        actorRole: 'Requester',
        action: 'Ticket Created',
        details: 'Submitted request.',
        type: 'STATUS_CHANGE',
      },
      {
        id: 'act-rcl-2',
        timestamp: '2026-09-14T11:15:00Z',
        actorId: 'usr-emp-1',
        actorName: 'Alex Rivera',
        actorRole: 'Requester',
        action: 'Ticket Recalled',
        details: 'Requester pulled back ticket before engineering execution commenced. Reason: Wrong RAM sizing.',
        type: 'RECALL',
        oldValue: 'SUBMITTED',
        newValue: 'RECALLED',
      },
    ],
    worklogs: [],
  },

  // 7. Change Management RFC
  {
    id: 'tkt-chg-007',
    ticketNumber: 'CHG-2026-000001',
    title: 'Firmware & PAN-OS 11.1 Security Upgrade on Perimeter Firewalls',
    description: 'Upgrade high-availability cluster paloalto-ha-perimeter from PAN-OS 11.0.2 to 11.1.0 to address CVE-2026-3849 critical SSL inspection vulnerability.',
    ticketType: 'Change Request',
    status: 'WAITING_FOR_CHANGE_WINDOW',
    priority: 'P2',
    impact: 'Enterprise',
    urgency: 'Medium',
    category: 'Infrastructure Maintenance',
    subcategory: 'Firewall Maintenance',
    service: 'Perimeter Security',
    department: 'Network & Security',
    requesterId: 'usr-l2-1',
    requesterName: 'Rachel Green',
    requesterEmail: 'l2.demo@enterprise-itsm.local',
    requesterDepartment: 'Network & Security',
    currentAssignmentGroup: 'Network & Security',
    currentAssigneeId: 'usr-l2-1',
    currentAssigneeName: 'Rachel Green',
    businessOwner: 'Evelyn Reed',
    affectedCIId: 'ci-fw-01',
    affectedCIName: 'paloalto-ha-perimeter',
    environment: 'PROD',
    createdAt: '2026-09-14T09:00:00Z',
    updatedAt: '2026-09-15T02:00:00Z',
    sla: {
      priority: 'P2',
      responseTargetMinutes: 60,
      resolutionTargetMinutes: 1440,
      responseSLAStart: '2026-09-14T09:00:00Z',
      resolutionSLAStart: '2026-09-14T09:00:00Z',
      resolutionSLATarget: '2026-09-16T09:00:00Z',
      elapsedMinutes: 480,
      pausedMinutes: 0,
      remainingMinutes: 960,
      percentageConsumed: 33.3,
      isPaused: false,
      isBreached: false,
      clockEvents: [],
    },
    approvals: [
      {
        id: 'app-chg-1',
        stageName: 'CAB (Change Advisory Board) Review',
        approverRole: 'Operations Manager',
        approverUserId: 'usr-ops-1',
        approverName: 'David Zhao',
        status: 'APPROVED',
        actionDate: '2026-09-14T15:00:00Z',
        comments: 'CAB approved window: Saturday 01:00 UTC.',
        isMandatory: true,
      },
      {
        id: 'app-chg-2',
        stageName: 'CISO Security Approval',
        approverRole: 'CISO',
        approverUserId: 'usr-ciso-1',
        approverName: 'Evelyn Reed',
        status: 'APPROVED',
        actionDate: '2026-09-14T16:20:00Z',
        comments: 'Security hotfix confirmed. Mandatory pre-checks required.',
        isMandatory: true,
      },
    ],
    tasks: [],
    activities: [
      {
        id: 'act-chg-1',
        timestamp: '2026-09-14T09:00:00Z',
        actorId: 'usr-l2-1',
        actorName: 'Rachel Green',
        actorRole: 'Cloud Engineer',
        action: 'RFC Submitted',
        details: 'Submitted Normal Change Request with rollback plan.',
        type: 'STATUS_CHANGE',
      },
    ],
    worklogs: [],
  },

  // 8. Longest ticket / SLA Breached example for Vendor Performance & Invoice review
  {
    id: 'tkt-sla-breached-08',
    ticketNumber: 'INC-2026-000008',
    title: 'Fiber Channel SAN Switch Blade 4 Hardware Port Failure',
    description: 'Hardware ASIC port failure on Brocade SAN switch. Vendor field engineer was delayed due to OEM spare part customs clearance.',
    ticketType: 'Incident',
    status: 'RESOLVED',
    priority: 'P2',
    impact: 'Department',
    urgency: 'High',
    category: 'Enterprise Storage & Backup',
    subcategory: 'Hardware Failure',
    service: 'SAN Fabric Core',
    department: 'Data Center Facilities',
    requesterId: 'usr-l1-1',
    requesterName: 'Kevin Patel',
    requesterEmail: 'l1.demo@enterprise-itsm.local',
    requesterDepartment: 'NOC & Monitoring',
    currentAssignmentGroup: 'Data Center Facilities',
    currentAssigneeId: 'usr-l3-1',
    currentAssigneeName: 'Vikram Seth',
    businessOwner: 'Marcus Vance',
    environment: 'PROD',
    createdAt: '2026-09-10T08:00:00Z',
    updatedAt: '2026-09-12T16:00:00Z',
    resolvedAt: '2026-09-12T16:00:00Z',
    resolutionSummary: 'OEM Field Engineer replaced faulty SFP+ blade on chassis. Port traffic restored.',
    resolutionCode: 'Hardware Replacement',
    sla: {
      priority: 'P2',
      responseTargetMinutes: 30,
      resolutionTargetMinutes: 240, // 4 hours
      responseSLAStart: '2026-09-10T08:00:00Z',
      responseSLAEnd: '2026-09-10T08:20:00Z',
      responseSLAMet: true,
      resolutionSLAStart: '2026-09-10T08:00:00Z',
      resolutionSLATarget: '2026-09-10T12:00:00Z',
      resolutionSLAEnd: '2026-09-12T16:00:00Z',
      elapsedMinutes: 3360, // 56 hours!
      pausedMinutes: 720,
      remainingMinutes: -2400,
      percentageConsumed: 620,
      isPaused: false,
      isBreached: true,
      clockEvents: [
        {
          id: 'clk-brk-1',
          eventType: 'STARTED',
          timestamp: '2026-09-10T08:00:00Z',
          actorName: 'System Engine',
        },
        {
          id: 'clk-brk-2',
          eventType: 'BREACHED',
          timestamp: '2026-09-10T12:00:00Z',
          actorName: 'SLA Daemon',
          reason: 'Resolution SLA Breached (Target was 4 hours)',
        },
      ],
    },
    thirdPartyDependency: {
      isThirdParty: true,
      providerName: 'Global Storage Solutions OEM Support',
      externalTicketNumber: 'OEM-BRC-882190',
      downtimeMinutes: 0, // Dual fabric redundancy prevented outage
      delayAttribution: 'OEM Cause',
      justification: 'Vendor delay: OEM spare part was delayed at national transit depot. SLA penalty clause applicable in monthly invoice.',
    },
    approvals: [],
    tasks: [],
    activities: [
      {
        id: 'act-brk-1',
        timestamp: '2026-09-10T12:00:00Z',
        actorId: 'system',
        actorName: 'SLA Engine',
        actorRole: 'Daemon',
        action: 'SLA Breached Notification Sent',
        details: 'Breached resolution SLA. Escalated notification to Operations Manager and Infra Head.',
        type: 'STATUS_CHANGE',
      },
    ],
    worklogs: [],
  },
];

export const SEEDED_KB_ARTICLES: KnowledgeArticle[] = [
  {
    id: 'kb-001',
    articleNumber: 'KB-2026-0001',
    title: 'Resolving MySQL "Too Many Connections" & Pruning Orphaned Sleep Threads',
    problem: 'Application returns "Error 1040: Too many connections" during traffic peaks.',
    symptoms: 'Database CPU is normal but applications receive connection refused timeouts.',
    cause: 'Application background workers fail to close persistent connections when idle.',
    resolution: '1. Increase max_connections dynamically: SET GLOBAL max_connections = 2500;\n2. Reduce wait_timeout: SET GLOBAL wait_timeout = 60;\n3. Prune sleeping threads using Percona Toolkit:\npt-kill --busy-time 60 --match-command Sleep --kill --print',
    workaround: 'Restart backend worker pools with maxPoolSize=15 constraint.',
    commands: 'mysql -e "SHOW STATUS LIKE \'Threads_connected\';"\npt-kill --busy-time 60 --kill',
    category: 'Database Administration',
    applicableSystems: ['MySQL 8.0', 'MariaDB', 'AWS RDS'],
    tags: ['database', 'mysql', 'connection-leak', 'p1-fix'],
    authorName: 'Vikram Seth',
    status: 'Published',
    createdFromTicketNumber: 'INC-2026-000005',
    views: 142,
    helpfulCount: 38,
    createdAt: '2026-09-13T13:00:00Z',
    updatedAt: '2026-09-13T14:30:00Z',
  },
  {
    id: 'kb-002',
    articleNumber: 'KB-2026-0002',
    title: 'Standard Operating Procedure: Cisco ASR9000 BGP Flap Mitigation',
    problem: 'Upstream transit provider fiber flapping causes core routing oscillation.',
    symptoms: 'High packet loss (>25%) and ping latency spikes across corporate WAN.',
    cause: 'Upstream fiber cut or unstable optical transceiver.',
    resolution: 'Apply BGP route dampening and prepend AS-PATH on the unstable peering session to steer traffic over secondary carrier.',
    commands: 'router bgp 65000\n neighbor 198.51.100.2 route-map PREPEND_OUT out',
    category: 'Network & Security',
    applicableSystems: ['Cisco ASR9000', 'IOS-XR', 'BGP Peering'],
    tags: ['network', 'bgp', 'cisco', 'outage'],
    authorName: 'Rachel Green',
    status: 'Published',
    createdFromTicketNumber: 'INC-2026-000002',
    views: 89,
    helpfulCount: 24,
    createdAt: '2026-09-15T05:30:00Z',
    updatedAt: '2026-09-15T05:30:00Z',
  },
];

export const VENDOR_PERFORMANCE_METRICS: VendorPerformanceSummary = {
  vendorName: 'Apex Cloud & Infrastructure Services Corp.',
  period: 'August 2026 - September 2026',
  contractRef: 'MSA-2024-INF-089',
  totalCalls: 48,
  callsByPriority: {
    P1: 4,
    P2: 12,
    P3: 22,
    P4: 10,
  },
  callsBySupportLevel: {
    L1: 18,
    L2: 21,
    L3: 9,
  },
  slaMetCount: 44,
  slaBreachedCount: 4,
  slaMetPercentage: 91.67,
  avgResolutionHours: 3.4,
  longestTicketHours: 56.0,
  pausedHoursTotal: 38.5,
  delayAttribution: {
    vendorDelayHours: 24.5,
    requesterDelayHours: 14.0,
    oemDelayHours: 32.0,
    thirdPartyDelayHours: 18.5,
    resourceDelayHours: 6.0,
  },
  reopenedCount: 2,
  repeatIncidentCount: 3,
  performanceScore: 88.5,
  managementReviewStatus: 'REVIEWED',
  managementComments: '4 SLA breaches recorded. Notice issued regarding SAN hardware spare delivery SLA. Invoice penalty of 5% recommended for line-item Storage Hardware support.',
};

export const SEEDED_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'aud-001',
    timestamp: '2026-09-15T04:00:00Z',
    actorId: 'usr-l1-1',
    actorName: 'Kevin Patel',
    actorRole: 'NOC L1',
    ipAddress: '10.240.2.14',
    action: 'TICKET_CREATE',
    targetType: 'TICKET',
    targetId: 'tkt-inc-003',
    targetIdentifier: 'INC-2026-000002',
    newValues: 'Status: IN_PROGRESS, Priority: P1, CI: cisco-asr9000-border-gw',
    reason: 'Automated SNMP Trap from Zabbix',
  },
  {
    id: 'aud-002',
    timestamp: '2026-09-15T02:30:00Z',
    actorId: 'usr-mgr-1',
    actorName: 'Sarah Jenkins',
    actorRole: 'Supervisor',
    ipAddress: '10.240.5.88',
    action: 'APPROVAL_GRANTED',
    targetType: 'APPROVAL',
    targetId: 'app-fw-1',
    targetIdentifier: 'REQ-2026-000004',
    newValues: 'Stage 1: Approved',
    reason: 'Verified business requirement with FinOps team',
  },
  {
    id: 'aud-003',
    timestamp: '2026-09-14T17:30:00Z',
    actorId: 'usr-l3-1',
    actorName: 'Vikram Seth',
    actorRole: 'Principal Systems Architect (L3)',
    ipAddress: '10.240.8.12',
    action: 'SLA_PAUSED',
    targetType: 'TICKET',
    targetId: 'tkt-inc-004',
    targetIdentifier: 'INC-2026-000003',
    oldValues: 'Status: IN_PROGRESS, isPaused: false',
    newValues: 'Status: ON_HOLD, isPaused: true, Reason: Waiting for Approved Maintenance Window',
    reason: 'Firmware controller flash requires 15-minute failover pause. Scheduled for tonight 02:00 AM UTC.',
  },
];
